default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  write:
    <<: *default
    database: postgresql_write
    host: localhost
    port: 15434
    username: postgres
    password: postgres
  read:
    <<: *default
    database: postgresql_read
    host: localhost
    port: 15435
    username: postgres
    password: postgres
    replica: true
test:
  <<: *default
  database: postgresql
  host: localhost
  port: 15434

production:
  <<: *default
  database: postgresql
  host: localhost
  port: 15434
