default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost
  port: 15434

development:
  <<: *default
  database: postgresql
  host: localhost
  port: 15434

test:
  <<: *default
  database: postgresql
  host: localhost
  port: 15434

production:
  <<: *default
  database: postgresql
  host: localhost
  port: 15434
