default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 15433

development:
  <<: *default
  database: postgresql
  host: 127.0.0.1
  port: 15433


test:
  <<: *default
  database: postgresql
  host: 127.0.0.1
  port: 15433

production:
  <<: *default
  database: postgresql
  host: 127.0.0.1
  port: 15433
